#!/usr/bin/env python

import optparse
import sys, os
import pprint
import MetagenomeDB as mdb

p = optparse.OptionParser(description = """Part of the MetagenomeDB toolkit.
Imports nucleotide or aminoacid sequences into the database. Those sequences
can be in any format supported by Biopython (see http://biopython.org/wiki/SeqIO).""")

g = optparse.OptionGroup(p, "Input")

g.add_option("-i", "--input", dest = "input_fn", metavar = "FILENAME",
	help = "Sequences to import (mandatory).")

g.add_option("-f", "--format", dest = "input_format", metavar = "STRING", default = "fasta",
	help = "Format of the sequences file (optional). Default: %default")

g.add_option("-s", "--sequence-property", dest = "sequence_properties", nargs = 2, action = "append", metavar = "KEY VALUE",
	help = """Property to annotate all sequences with (optional); this option
can be used multiple times.""")

g.add_option("-C", "--collection", dest = "collection_name", metavar = "STRING",
	help = "Name of the collection the sequences belong to (mandatory).")

g.add_option("-c", "--collection-property", dest = "collection_properties", nargs = 2, action = "append", metavar = "KEY VALUE",
	help = """Property to annotate the collection with (optional); this option
can be used multiple times.""")

g.add_option("-r", "--relationship-property", dest = "relationship_properties", nargs = 2, action = "append", metavar = "KEY VALUE",
	help = """Property to annotate all relationships between sequences and the
collection (optional); this option can be used multiple times.""")

p.add_option_group(g)

g = optparse.OptionGroup(p, "Errors handling")

g.add_option("--ignore-duplicates", dest = "ignore_duplicates", action = "store_true", default = False,
	help = "If set, ignore duplicate objects errors.")

p.add_option_group(g)

mdb.tools.include("connection_options", globals())

p.add_option("-v", "--verbose", dest = "verbose", action = "store_true", default = False)
p.add_option("--no-progress-bar", dest = "display_progress_bar", action = "store_false", default = True)
p.add_option("--dry-run", dest = "dry_run", action = "store_true", default = False)
p.add_option("--version", dest = "display_version", action = "store_true", default = False)

p.add_option_group(g)

(p, a) = p.parse_args()

def error (msg):
	msg = str(msg)
	if msg.endswith('.'):
		msg = msg[:-1]
	print >>sys.stderr, "ERROR: %s." % msg
	sys.exit(1)

if (p.display_version):
	print mdb.version
	sys.exit(0)

if (p.input_fn == None):
	error("a sequence file must be provided")

if (not os.path.exists(p.input_fn)):
	error("file '%s' not found" % p.input_fn)

if (not p.collection_name) and (not p.collection_properties):
	error("a collection name or description must be provided")

#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

if (p.verbose):
	mdb.max_verbosity()

try:
	mdb.connect(**connection_parameters)
except Exception as msg:
	error(msg)

# Creation of a collection
if (p.collection_properties):
	m = {}
	for (key, value) in p.collection_properties:
		m[key] = mdb.tools.parse_value_and_modifier(value)

	if ("_id" in m):
		print >>sys.stderr, "WARNING: a '_id' field was found in the collection description and ignored."
		del m["_id"]

	if ("name" in m) and (mdb.Collection.find_one({"name": m["name"]}) != None):
		error("duplicate collection '%s'" % m["name"])

	try:
		collection = mdb.Collection(m)
		collection.commit()

	except ValueError as msg:
		error("malformed collection description: %s" % msg)

# Retrieval of an existing collection
elif (p.collection_name):
	collection = mdb.Collection.find_one({"name": p.collection_name})

	if (collection == None):
		error("unknown collection '%s'" % p.collection_name)

if (p.relationship_properties):
	m = {}
	for (key, value) in p.relationship_properties:
		m[key] = mdb.tools.parse_value_and_modifier(value)

	p.relationship_properties = m
else:
	p.relationship_properties = {}

if (p.sequence_properties):
	m = []
	for (key, value) in p.sequence_properties:
		m.append((key, mdb.tools.parse_value_and_modifier(value)))

	p.sequence_properties = m

#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

try:
	from Bio import SeqIO
except:
	error("the BioPython library is not installed.\nTry 'easy_install biopython'")

def read():
	try:
		parser = SeqIO.parse(p.input_fn, p.input_format)
	except ValueError as msg:
		error(msg)

	return parser

print "importing '%s' (%s format) ..." % (p.input_fn, p.input_format)

print "  checking the input file ..."

seen = {}
for record in read():
	if (record.id in seen):
		error("duplicate sequence '%s'" % record.id)

	seen[record.id] = True

n = len(seen)

if (n == 0):
	error("the input file contains no sequence")

#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

print "  importing sequences ..."

pb = mdb.tools.progressbar(n)
n = 0

for record in read():
	entry = {
		"name": record.id,
		"sequence": str(record.seq),
		"length": len(record.seq),
	}

	if (hasattr(record, "description")):
		entry["description"] = record.description

	# see http://en.wikipedia.org/wiki/FASTQ_format#Variations
	# for an explanation of the different quality scales
	if ("phred_quality" in record.letter_annotations):
		entry["quality"] = {
			"values": record.letter_annotations["phred_quality"],
			"scale": "PHRED"
		}

	elif ("solexa_quality" in record.letter_annotations):
		entry["quality"] = {
			"values": record.letter_annotations["solexa_quality"],
			"scale": "Solexa"
		}

	if (p.sequence_properties):
		for (key, value) in p.sequence_properties:
			if (key in entry):
				error("reserved field '%s'" % key)

			entry[key] = value

	try:
		sequence = mdb.Sequence(entry)

		if (p.dry_run):
			print pprint.pformat(sequence.get_properties())
			continue

		sequence.add_to_collection(collection, p.relationship_properties)
		sequence.commit()

	except (mdb.errors.DBConnectionError, mdb.errors.DBOperationError) as msg:
		error(msg)

	except mdb.errors.DuplicateObjectError as msg:
		if (p.ignore_duplicates):
			print >>sys.stderr, "WARNING: %s" % str(msg)
		else:
			error(msg)

	n += 1
	if (p.display_progress_bar):
		pb.display(n)

if (p.display_progress_bar):
	pb.clear()

print "    %s sequence%s imported" % ("{:,}".format(n), {True: 's', False: ''}[n > 1])

if (p.dry_run):
	print "done (dry run)."
else:
	print "done."
