#!/usr/bin/env python

import optparse, os, sys

p = optparse.OptionParser(description = """Part of the MetagenomeDB toolkit.
Remove objects from the database. EXPERIMENTAL.""")

g = optparse.OptionGroup(p, "Target")

g.add_option("--all", dest = "remove_all", action = "store_true", default = False,
	help = "Remove all content in the database.")

g.add_option("--type", dest = "remove_type", metavar = "STRING",
	help = "Remove all objects of a given type.")

g.add_option("--date-range", dest = "remove_by_date_range", nargs = 2, metavar = "DATE1 DATE2",
	help = "Remove all objects which creation date is between two given dates (or 'now')")

p.add_option_group(g)

p.add_option("-v", "--verbose", dest = "verbose", action = "store_true", default = False)

g = optparse.OptionGroup(p, "Connection")

g.add_option("--host", dest = "connection_host", metavar = "HOSTNAME", default = "localhost",
	help = "Host name or IP address of the MongoDB server (optional). Default: %default")

g.add_option("--port", dest = "connection_port", metavar = "INTEGER", default = 27017,
	help = "Port of the MongoDB server (optional). Default: %default")

g.add_option("--db", dest = "connection_db", metavar = "STRING", default = "MetagenomeDB",
	help = "Name of the database in the MongoDB server (optional). Default: '%default'")

g.add_option("--user", dest = "connection_user", metavar = "STRING", default = '',
	help = "User for the MongoDB server connection (optional). Default: '%default'")

g.add_option("--password", dest = "connection_password", metavar = "STRING", default = '',
	help = "Password for the MongoDB server connection (optional). Default: '%default'")

p.add_option_group(g)

(p, a) = p.parse_args()

def error (msg):
	if str(msg).endswith('.'):
		msg = str(msg[:-1])
	print >>sys.stderr, "ERROR: %s." % msg
	sys.exit(1)

#:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

import MetagenomeDB as mdb
import datetime, re

if (p.verbose):
	mdb.max_verbosity()

if (p.connection_host or p.connection_port or p.connection_db or p.connection_user or p.connection_password):
	try:
		mdb.connect(p.connection_host, p.connection_port, p.connection_db, p.connection_user, p.connection_password)
	except Exception as msg:
		error(msg)

collections = {
	"Collection": mdb.Collection,
	"Sequence": mdb.Sequence,
}

DATE = re.compile("([0-9]+)([ywdhms])")

def convert_date (date):
	if (date.lower() == "now"):
		return datetime.datetime.utcnow()

	m = list(DATE.finditer(date.lower()))
	if (len(m) == 0):
		raise Exception("Invalid date '%s'" % date)

	delta = {}
	for item in m:
		value, key = item.groups()

		key = {
			"y": "year",
			"w": "weeks",
			"d": "days",
			"h": "hours",
			"m": "minutes",
			"s": "seconds",
		}[key]

		delta[key] = int(value)

	delta = datetime.timedelta(**delta)
	return datetime.datetime.utcnow() - delta

try:
	if (p.remove_all):
		print "Removing all content."

		for collection in collections:
			mdb.connection().drop_collection(collection)

		sys.exit(0)

	if (p.remove_type):
		print "Removing all content from '%s'" % p.remove_type

		try:
			collection = collections[p.remove_type]
		except AttributeError:
			raise Exception("Unknown object type '%s'" % p.remove_type)

		collection.remove_all()
		sys.exit(0)

	if (p.remove_by_date_range):
		date1, date2 = p.remove_by_date_range

		date1 = convert_date(date1)
		date2 = convert_date(date2)

		if (date1 > date2):
			date2, date1 = date1, date2

		print "Removing all content created between %s and %s" % (date1, date2)

		for collection in collections.values():
			for object in collection.find(creation_time = { "$gte": date1, "$lte": date2 }):
				print object

except Exception as msg:
	error(msg)
