#!/usr/bin/env python

import MetagenomeDB as mdb
import sys

mdb.set_debug_level(1)

try:
	mdb.Collection.remove_all()
	mdb.Sequence.remove_all()
	mdb.Relationship.remove_all()

except Exception as msg:
	print >>sys.stderr, "ERROR: %s" % msg
	sys.exit(1)

